import './globals.css'
import './home.css'
import './money.css'
import { Inter, Archivo } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next'
import { SITE } from '../lib/site'

const inter = Inter({ subsets: ['latin'], variable: '--font-body', display: 'swap' })
const archivo = Archivo({
  subsets: ['latin'],
  variable: '--font-display',
  display: 'swap',
})
import { organizationSchema, websiteSchema } from '../lib/schema'
import JsonLd from '../components/seo/JsonLd'
import Tracking from '../components/seo/Tracking'

const LIVE_REVIEWS_URL = 'https://bluepeekdashboard.com.au/api/public/reviews'

// The Google Maps URL for Bluepeek's profile, from the live reviews feed, so the
// organisation schema's sameAs links to the real Business Profile.
async function getLiveProfile() {
  try {
    const res = await fetch(LIVE_REVIEWS_URL, { next: { revalidate: 3600 } })
    if (!res.ok) return null
    const j = await res.json()
    return j?.ok && j.mapsUrl ? { mapsUrl: j.mapsUrl } : null
  } catch {
    return null
  }
}

export const metadata = {
  verification: { google: ["cHdpD0nUSxKaZRO8R36srahgiZm2AkvAraSEvueRkC0", "CwTuTcWWsYurouCWrDbDmlItyxjk6FAjW8SU3dTJjD0"] },
  metadataBase: new URL(SITE.url),
  title: {
    default: 'Bluepeek | Gold Coast Google Ads, Web Design & Reviews',
    template: '%s | Bluepeek',
  },
  description: SITE.description,
  authors: [{ name: 'Bluepeek' }],
  creator: 'Bluepeek',
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    locale: 'en_AU',
    url: SITE.url,
    siteName: SITE.name,
    title: 'Bluepeek | Gold Coast Google Ads, Web Design & Reviews',
    description: SITE.description,
    // og:image is generated by app/opengraph-image.jsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Bluepeek | Gold Coast Google Ads, Web Design & Reviews',
    description: SITE.description,
    // twitter image falls back to app/opengraph-image.jsx
  },
  icons: {
    icon: [
      { url: '/favicon-16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32.png', sizes: '32x32', type: 'image/png' },
    ],
    other: [{ rel: 'mask-icon', url: '/mask-icon.svg', color: '#0B3ED9' }],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 },
  },
}

export const viewport = {
  themeColor: '#0B3ED9',
}

export default async function RootLayout({ children }) {
  const liveProfile = await getLiveProfile()
  return (
    <html lang="en-AU" className={`${inter.variable} ${archivo.variable}`} suppressHydrationWarning>
      <body suppressHydrationWarning>
        {/* Scroll reveals are framer-motion, which renders them at opacity:0 until
            hydration. Without JS that leaves the page body blank, so force every
            inline-hidden element visible. JS users are unaffected. */}
        <noscript>
          <style>{`[style*="opacity:0"],[style*="opacity: 0"]{opacity:1!important;transform:none!important}`}</style>
        </noscript>
        {children}
        <JsonLd data={organizationSchema(liveProfile)} />
        <JsonLd data={websiteSchema()} />
        <Analytics />
        <Tracking />
      </body>
    </html>
  )
}
