import './globals.css'
import { Inter, Plus_Jakarta_Sans } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next'
import { SITE } from '../lib/site'

const inter = Inter({ subsets: ['latin'], variable: '--font-body', display: 'swap' })
const jakarta = Plus_Jakarta_Sans({ subsets: ['latin'], weight: ['500', '600', '700', '800'], variable: '--font-heading', display: 'swap' })
import { organizationSchema, websiteSchema } from '../lib/schema'
import JsonLd from '../components/seo/JsonLd'

const LIVE_REVIEWS_URL = 'https://bluepeekdashboard.com.au/api/public/reviews'

// Fetched at request time (revalidated hourly) so the SEO schema's rating/review
// count stays in sync with the real Google Business Profile, not a stale snapshot.
async function getLiveReviews() {
  try {
    const res = await fetch(LIVE_REVIEWS_URL, { next: { revalidate: 3600 } })
    if (!res.ok) return null
    const j = await res.json()
    if (!j?.ok || !j.reviews?.length) return null
    return {
      agg: { ratingValue: String(j.ratingValue), reviewCount: j.reviewCount, bestRating: '5' },
      reviews: j.reviews.map(r => ({ author: r.author, rating: r.rating, text: r.text })),
    }
  } catch {
    return null
  }
}

export const metadata = {
  verification: { google: ["cHdpD0nUSxKaZRO8R36srahgiZm2AkvAraSEvueRkC0", "CwTuTcWWsYurouCWrDbDmlItyxjk6FAjW8SU3dTJjD0"] },
  metadataBase: new URL(SITE.url),
  title: {
    default: 'Bluepeek - Gold Coast Website Design & AI Automation',
    template: '%s | Bluepeek',
  },
  description: SITE.description,
  keywords: [
    'Gold Coast website design', 'web design Gold Coast', 'AI automation Gold Coast',
    'small business websites Gold Coast', 'website designer Gold Coast', 'local SEO Gold Coast',
    'Perth website design', 'small business websites Perth', 'AI automation Perth',
    'lead capture websites', 'websites for tradies', 'web design Australia', 'Bluepeek',
  ],
  authors: [{ name: 'Bluepeek' }],
  creator: 'Bluepeek',
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    locale: 'en_AU',
    url: SITE.url,
    siteName: SITE.name,
    title: 'Bluepeek - Gold Coast Website Design & AI Automation',
    description: SITE.description,
    // og:image is generated by app/opengraph-image.jsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Bluepeek - Gold Coast Website Design & AI Automation',
    description: SITE.description,
    // twitter image falls back to app/opengraph-image.jsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 },
  },
}

export default async function RootLayout({ children }) {
  const liveReviews = await getLiveReviews()
  return (
    <html lang="en-AU" className={`${inter.variable} ${jakarta.variable}`} suppressHydrationWarning>
      <body suppressHydrationWarning>
        {children}
        <JsonLd data={organizationSchema(liveReviews)} />
        <JsonLd data={websiteSchema()} />
        <Analytics />
      </body>
    </html>
  )
}
